feat(rate): add clearable prop
tusen-ai/naive-ui pull request #3567
Opened 2022-08-22 03:33 UTC by doom-9

2022-08-22 03:34 UTC, doom-9 commented
再次点击时重置，这种交互行不行

2022-08-22 12:29 UTC, amadeus711 commented on src/rate/demos/zhCN/clearable.demo.vue
> +# 基础用法
重置

2022-08-22 12:29 UTC, amadeus711 commented on src/rate/demos/zhCN/clearable.demo.vue
> +# 基础用法
添加英文 demo

2022-08-22 12:31 UTC, amadeus711 requested changes

2022-08-22 12:31 UTC, amadeus711 commented on src/rate/src/Rate.tsx
> +      if (clearable && value === mergedValue.value) {
感觉这种逻辑还是不要写在 `doUpdateValue` 内，单独在外面写吧，尽可能让函数内部纯净

2022-08-23 15:03 UTC, amadeus711 approved these changes

2022-08-24 16:56 UTC, merged