fix: 修复谷歌、edge浏览器106版本下拖动tree，出现白屏现象 。拖拽tree页面白屏，关闭#3909
tusen-ai/naive-ui pull request #3912
Opened 2022-10-22 10:55 UTC by zhengdaonian

2022-10-23 11:58 UTC, 07akioni commented on src/tree/src/styles/index.cssr.ts
> +    z-index: 0;
不加 translateZ 的 transform 意义怎么说？有别的做法吗？

2022-10-23 12:47 UTC, zhengdaonian commented on src/tree/src/styles/index.cssr.ts
> +    z-index: 0;
我查了一下，该问题是浏览器问题,大概11月份107版本会修复，是否需要兼容106版本浏览器修改代码。https://bugs.chromium.org/p/chromium/issues/detail?id=1373787&q=drag&can=2

至于为什么不用translateZ，这里加了之后会浏览器会硬件加速，对于清晰度和浏览器拖动效果可能会有影响。
如果使用translateZ，这里得z-index:0就可以不用加了

2022-10-23 12:58 UTC, 07akioni commented on src/tree/src/styles/index.cssr.ts
> +    z-index: 0;
那感觉 translatez 会比较简单，改 zindex 的话要注意一下不要影响一些 hover 背景的顺序

2022-10-23 13:00 UTC, zhengdaonian commented on src/tree/src/styles/index.cssr.ts
> +    z-index: 0;
好的,那我改成translate3d

2022-10-24 13:01 UTC, amadeus711 requested changes

2022-10-24 13:01 UTC, amadeus711 commented on CHANGELOG.en-US.md
> +- Fix `n-tree` 在谷歌、edge 浏览器 106 版本下拖动 tree，出现白屏现象，关闭 [#3909](https://github.com/tusen-ai/naive-ui/issues/3909)
写错位置了，不能写在已发布的版本里

2022-10-24 13:01 UTC, amadeus711 commented on CHANGELOG.zh-CN.md
> +- 修复 `n-tree` 在谷歌、edge 浏览器 106 版本下拖动 tree，出现白屏现象，关闭 [#3909](https://github.com/tusen-ai/naive-ui/issues/3909)
同上

2022-10-24 13:01 UTC, amadeus711 commented
处理一下两个 pr，可以使用 `git cherry-pick`

2022-10-24 13:36 UTC, closed without merging