feat(button): adds `icon`  prop
tusen-ai/naive-ui pull request #4011
Opened 2022-11-09 08:51 UTC by jizai1125

closes #4007

2022-11-10 03:58 UTC, amadeus711 requested changes

2022-11-10 03:58 UTC, amadeus711 commented on CHANGELOG.en-US.md
> +- `n-button` adds `icon` prop，closes [#4007](https://github.com/tusen-ai/naive-ui/issues/4007)
renderIcon

2022-11-10 04:14 UTC, jizai1125 commented on CHANGELOG.en-US.md
> +- `n-button` adds `icon` prop，closes [#4007](https://github.com/tusen-ai/naive-ui/issues/4007)
改成接收函数么？() => VNodeChild

2022-11-10 13:18 UTC, amadeus711 commented on CHANGELOG.en-US.md
> +- `n-button` adds `icon` prop，closes [#4007](https://github.com/tusen-ai/naive-ui/issues/4007)
> 改成接收函数么？() => VNodeChild

props 上统一接收函数吧，这样未来灵活一点

2022-11-11 03:09 UTC, amadeus711 approved these changes

2022-11-12 07:22 UTC, merged