feat(n-tree): add expanded in render-switcher-icon func
tusen-ai/naive-ui pull request #4017
Opened 2022-11-10 06:22 UTC by notail

2022-11-10 13:15 UTC, amadeus711 requested changes
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/46394163/201101132-9556e1b1-c28f-4631-b916-d2818ac3e576.png">
请添加中英文 API 文档

2022-11-10 14:18 UTC, notail commented
> <img alt="image" width="1316" src="https://user-images.githubusercontent.com/46394163/201101132-9556e1b1-c28f-4631-b916-d2818ac3e576.png">
> 
> 请添加中英文 API 文档

done

2022-11-11 03:01 UTC, amadeus711 commented on src/tree/demos/enUS/index.demo-entry.md
> +| render-switcher-icon | `(options: { expanded: boolean, selected: boolean } | void) => VNodeChild` | `undefined` | Render function of option switcher icon. | 2.24.0 |
```suggestion
| render-switcher-icon | `(options: { expanded: boolean, selected: boolean }) => VNodeChild` | `undefined` | Render function of option switcher icon. | 2.24.0 |
```

2022-11-11 03:06 UTC, amadeus711 approved these changes

2022-11-11 03:06 UTC, amadeus711 commented on src/tree/demos/zhCN/index.demo-entry.md
> +| render-switcher-icon | `(options: { expanded: boolean, selected: boolean } | void) => VNodeChild` | `undefined` | 节点展开开关的渲染函数 | 2.24.0 |
```suggestion
| render-switcher-icon | `(options: { expanded: boolean, selected: boolean }) => VNodeChild` | `undefined` | 节点展开开关的渲染函数 | 2.24.0, `optimize`: NEXT_VERSION |
```

2022-11-12 13:31 UTC, merged