fix(n-log): `silent` attribute spelling problem
tusen-ai/naive-ui pull request #4876
Opened 2023-05-30 05:50 UTC by jahnli

close [#4875](https://github.com/tusen-ai/naive-ui/issues/4875)

2023-06-01 01:37 UTC, amadeus711 requested changes

2023-06-01 01:37 UTC, amadeus711 commented on CHANGELOG.en-US.md
> +### Fixes
This should be classified as breaking change

2023-06-01 01:43 UTC, jahnli commented
finished

2023-06-02 02:08 UTC, jahnli commented on CHANGELOG.en-US.md
> +- Fix `n-log` 的 `silent` attribute spelling problem, closes [#4875](https://github.com/tusen-ai/naive-ui/issues/4875).
dowe

2023-06-05 02:38 UTC, amadeus711 approved these changes

2023-06-08 14:12 UTC, merged