fix: Input props onKeydown is Array
tusen-ai/naive-ui pull request #5124
Opened 2023-08-02 09:46 UTC by liulinboyi

## Issue
If use like this:
```vue
<template>
  <n-input
    @keydown.ctrl.c="handleDownKey"
    @keydown.ctrl.a="handleDownKey"
  />
</template>

<script setup lang="ts">
import { NInput } from "naive-ui";

const handleDownKey = () => {
  console.log("key down pressed");
};
</script>
```
will throw Error
![image](https://github.com/tusen-ai/naive-ui/assets/41336612/bd31c10b-1e82-4259-a5e0-0c61426af7c3)

the reason is the `props.onKeydown` maybe `Array`.

## Link
https://codesandbox.io/p/sandbox/blissful-rubin-wz7sfn?file=%2Fsrc%2FApp.vue%3A16%2C1

2023-08-03 01:39 UTC, amadeus711 requested changes

2023-08-03 01:39 UTC, amadeus711 commented on src/input/src/Input.tsx
> +      if (props.onKeydown) {
```suggestion
      if (props.onKeydown) call(props.onKeydown, e)
```

2023-08-03 02:39 UTC, liulinboyi commented on src/input/src/Input.tsx
> +      if (props.onKeydown) {
ok，Cool！

2023-08-04 01:55 UTC, amadeus711 approved these changes

2023-08-04 01:56 UTC, merged