fix(n-split): `modified `default-size` panel not updated issue
tusen-ai/naive-ui pull request #5527
Opened 2024-01-02 12:32 UTC by jahnli

close https://github.com/tusen-ai/naive-ui/issues/5526

2024-01-02 14:21 UTC, OrbisK approved these changes

2024-01-02 14:21 UTC, OrbisK commented on CHANGELOG.en-US.md
> +- Fix `n-split` Modified `default-size` panel not updated issue
```suggestion
- Fix `n-split` Modified `default-size` panel not updated issue.
```
😄

2024-01-03 01:20 UTC, jahnli commented
This part of the API may have to be re-implemented, I will re-open a PR

2024-01-03 10:38 UTC, OrbisK requested changes

2024-01-03 10:38 UTC, OrbisK commented on CHANGELOG.en-US.md
> +- `n-split` adds `watch-props` prop, closes [#5526](https://github.com/tusen-ai/naive-ui/issues/5526)
```suggestion
- `n-split` adds `watch-props` prop, closes [#5526](https://github.com/tusen-ai/naive-ui/issues/5526).
```

2024-01-03 10:38 UTC, OrbisK commented on src/split/demos/enUS/index.demo-entry.md
> +| watch-props | `Array<defaultSize>` | `undefined` | Default prop names that needed to be watched. Components will be updated after the prop is changed. Note: the `watch-props` itself is not reactive
```suggestion
| watch-props | `Array<'defaultSize'>` | `undefined` | Default prop names that needed to be watched. Components will be updated after the prop is changed. Note: the `watch-props` itself is not reactive. | NEXT_VERSION |
```

2024-01-03 10:38 UTC, OrbisK commented on src/split/demos/zhCN/index.demo-entry.md
> +| watch-props | `Array<defaultSize>` | `undefined` | 需要检测变更的默认属性，检测后组件状态会更新。注意：`watch-props` 本身不是响应式的 | 2.36.0 |
```suggestion
| watch-props | `Array<'defaultSize'>` | `undefined` | 需要检测变更的默认属性，检测后组件状态会更新。注意：`watch-props` 本身不是响应式的 | NEXT_VERSION |
```

2024-01-03 10:40 UTC, jahnli commented on src/split/demos/zhCN/index.demo-entry.md
> +| watch-props | `Array<defaultSize>` | `undefined` | 需要检测变更的默认属性，检测后组件状态会更新。注意：`watch-props` 本身不是响应式的 | 2.36.0 |
:zany_face:

2024-01-03 10:49 UTC, OrbisK approved these changes

2024-01-03 10:49 UTC, OrbisK commented on CHANGELOG.zh-CN.md
> +- 修复 `n-split` 修改 `default-size` 面板未更新问题
english translation missing 😄

2024-01-03 16:05 UTC, Sepush commented on src/split/src/Split.tsx
> +      watch(
这里 watchEffect 应该简单一点

2024-01-12 00:40 UTC, songjianet approved these changes

2024-01-23 11:37 UTC, merged