feat(split): add size and on-update:size, controlled properties
tusen-ai/naive-ui pull request #5582
Opened 2024-01-11 03:35 UTC by XueHua-s

2024-01-11 03:36 UTC, XueHua-s commented
feat(split): add size and on-update:size, controlled properties

2024-01-11 03:48 UTC, XueHua-s commented
更改了一些，自己文档写错的地方

2024-01-11 04:07 UTC, XueHua-s commented
增加, 使用受控值的案例

2024-01-11 04:34 UTC, XueHua-s commented
修复最大最小值的问题.

2024-01-12 13:10 UTC, OrbisK requested changes
Thank you for your contribution 🚀

2024-01-12 13:10 UTC, OrbisK commented on src/version.ts
> +export default '2.37.4'
please dont update this in PR

2024-01-12 13:10 UTC, OrbisK commented on src/split/src/Split.tsx
> +    default: 0
not sure if this should default to 0. this should default to undefined so default-size will work and 0 as value should still be possible

2024-01-12 13:10 UTC, OrbisK commented on CHANGELOG.en-US.md
> +-Feat `n-split`'s `size` and `on-update:size` add size and on-update:size, controlled properties.
```suggestion
- Add `n-split` `size` prop and `on-update:size` event.
```

2024-01-17 02:08 UTC, XueHua-s commented
The changes have been made

2024-01-17 10:14 UTC, OrbisK requested changes

2024-01-17 10:14 UTC, OrbisK commented on src/split/demos/enUS/index.demo-entry.md
> +| on-update:size | `(value: number) => void` | `undefined` | When a controlled property is used, it is triggered when the size property of the component changes | 2.37.4 |
```suggestion
| size | `number` | `undefined` | Split is the controlled split size, with 0-1 representing the percentage | NEXT_VERSION |
| on-update:size | `(value: number) => void` | `undefined` | When a controlled property is used, it is triggered when the size property of the component changes | NEXT_VERSION |
```
see https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md#关于文档和变更日志的格式

2024-01-17 10:14 UTC, OrbisK commented on src/split/demos/zhCN/index.demo-entry.md
> +| on-update:size | `(value: number) => void` | `undefined` | 使用受控属性时, 组件size属性变化时触发 | 2.37.4 |
```suggestion
| size | `number` | `undefined` | Split 的受控分割大小，0-1 代表百分比 | NEXT_VERSION |
| on-update:size | `(value: number) => void` | `undefined` | 使用受控属性时, 组件size属性变化时触发 | NEXT_VERSION |
```

2024-01-17 10:14 UTC, OrbisK commented on src/split/src/Split.tsx
> +      )
if props.size changes it will trigger currentSize and will trigger @update:size.

2024-01-17 10:19 UTC, OrbisK commented on src/split/src/Split.tsx
> +      )
i guess you can copy paste some code from checkbox for default and prop merging:
https://github.com/tusen-ai/naive-ui/blob/fce7b64ead4ba18d26b0115dc500303fdd70b3fc/src/checkbox/src/Checkbox.tsx#L153

2024-01-17 10:19 UTC, OrbisK commented
> The changes have been made

Thank you for your additonal work. There are some small adjustments left todo.

2024-01-19 17:16 UTC, XueHua-s commented
I have used the merge method with reference to the code in another file.

2024-01-22 02:07 UTC, liuyang0826 commented
最好是在props增加onUpdateSize和onUpdat:size事件，和其他组件保持一致

2024-01-22 06:12 UTC, XueHua-s commented
> @XueHua-s 
Added type onUpdate:size

2024-01-22 06:12 UTC, XueHua-s commented
> @XueHua-s 最好是在props增加onUpdateSize和onUpdat:size事件，和其他组件保持一致

Added type onUpdate:size

2024-01-22 06:16 UTC, XueHua-s commented
Added type onUpdate:size

2024-01-23 11:02 UTC, merged

2024-01-23 11:10 UTC, 07akioni commented
Basically good. For needed changes, you can see what I've done in 7cbaeaa4b