fix(FormItem): validation input or change and blur, The animation triggers twice
tusen-ai/naive-ui pull request #5585
Opened 2024-01-11 06:35 UTC by XueHua-s

2024-01-11 06:35 UTC, XueHua-s commented
n-form表单错误信息动画优化
当form表单的rule设置了多个trigger，比如trigger: ['input', 'blur']，此时input会触发错误信息，blur也会触发错误信息，错误出现会有动画效果，导致页面错误信息展示再闪一次出现。
1、打开官网示例：https://www.naiveui.com/zh-CN/os-theme/components/form
2、在年龄输入框中输入任意值并点击其他地方让输入框失去焦点
3、再次点击输入框，将内容删除，此时会出现必填的校验报错，再点击其他地方让输入框失去焦点，此时会再次出现必填项的错误校验信息

2024-01-11 13:38 UTC, OrbisK requested changes
Thank you for you contribution.

Before further review, please add the missing changelog entries. Please see [CONTRIBUTING.md](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md#关于文档和变更日志的格式).

2024-01-11 13:38 UTC, OrbisK commented on package.json
> +  "version": "2.37.4",
this should not be changed within a pr.

2024-01-12 00:56 UTC, XueHua-s commented
Adjusted the wrong place

2024-01-12 01:03 UTC, XueHua-s commented on package.json
> +  "version": "2.37.4",
The wrong PR has been adjusted

2024-01-23 16:41 UTC, 07akioni commented on CHANGELOG.zh-CN.md
> +- 修复 `form-item`'s `validation` input或change后, 再blur，动画触发两次
```suggestion
- 修复 `form-item`'s `validation` input 或 change 后，再blur，动画触发两次
```

2024-01-23 17:17 UTC, 07akioni commented
The issue is actually a bug, which caused by accidentally validation restoration under unexpected behavior. It's fixed in https://github.com/tusen-ai/naive-ui/commit/a604c4bcd886bc13a003d67026ea9b233d1a5ad4

2024-01-23 17:17 UTC, closed without merging