fix(scrollbar): Fix typo in aria-hidden
tusen-ai/naive-ui pull request #5589
Opened 2024-01-11 18:22 UTC by becem-gharbi

This PR fixes a typo in `aria-hidden` attribute that affects accessibility.

2024-01-12 10:29 UTC, OrbisK approved these changes

2024-01-12 13:04 UTC, OrbisK requested changes
Please add Changelogentries. See Contributing.md

2024-01-12 14:06 UTC, OrbisK commented
One more thing: 
> please add changelog to `CHANGELOG.zh-CN.md` & `CHANGELOG.en-US.md` in the PR. You need to add changelog to both files. You can use English in both file. The develop team will translate it later.
- from PR template should be better documented

2024-01-14 16:31 UTC, OrbisK approved these changes

2024-01-15 00:35 UTC, songjianet approved these changes

2024-01-22 07:32 UTC, kirklin approved these changes

2024-01-23 11:00 UTC, merged