feat(slider): aria support
tusen-ai/naive-ui pull request #5716
Opened 2024-02-25 03:47 UTC by imguolao

Slider support aria.

References:
1. https://www.w3.org/WAI/ARIA/apg/patterns/slider/
2. https://www.w3.org/WAI/ARIA/apg/patterns/slider-multithumb/
3. https://w3c.github.io/aria/#slider

2024-02-27 13:56 UTC, OrbisK approved these changes

2024-03-04 00:51 UTC, songjianet requested changes

2024-03-04 00:51 UTC, songjianet commented on src/slider/tests/Slider.spec.ts
> +    )
wrapper.unmount()

2024-03-04 00:51 UTC, songjianet commented on src/slider/tests/Slider.spec.ts
> +    expect(handle.attributes('aria-disabled')).toBe('true')
wrapper.unmount()

2024-03-11 10:14 UTC, merged